// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6PCazQnnsX-D9w_94W12V6GjRuVfbes8',
    appId: '1:156261409024:web:a21a91417054cab85f13e5',
    messagingSenderId: '156261409024',
    projectId: 'gdg-translator',
    authDomain: 'gdg-translator.firebaseapp.com',
    storageBucket: 'gdg-translator.firebasestorage.app',
    measurementId: 'G-E2NV291ZRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBSDUXOV-iCs3imdr3UJJ02lipIsM8e0I',
    appId: '1:156261409024:android:1891919263b366125f13e5',
    messagingSenderId: '156261409024',
    projectId: 'gdg-translator',
    storageBucket: 'gdg-translator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmTTRJL_otdlEp7lc1fq8ixW7ukzP0IBI',
    appId: '1:156261409024:ios:c4fc6b7948a99e3f5f13e5',
    messagingSenderId: '156261409024',
    projectId: 'gdg-translator',
    storageBucket: 'gdg-translator.firebasestorage.app',
    iosBundleId: 'com.example.translator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmTTRJL_otdlEp7lc1fq8ixW7ukzP0IBI',
    appId: '1:156261409024:ios:c4fc6b7948a99e3f5f13e5',
    messagingSenderId: '156261409024',
    projectId: 'gdg-translator',
    storageBucket: 'gdg-translator.firebasestorage.app',
    iosBundleId: 'com.example.translator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6PCazQnnsX-D9w_94W12V6GjRuVfbes8',
    appId: '1:156261409024:web:51444abae9ef29225f13e5',
    messagingSenderId: '156261409024',
    projectId: 'gdg-translator',
    authDomain: 'gdg-translator.firebaseapp.com',
    storageBucket: 'gdg-translator.firebasestorage.app',
    measurementId: 'G-BKLFH6GZNW',
  );

}